### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by ImZeazy** [Exploding-Creeper/Hyper-Lighting#10]
Hello again! Campfires are working correctly with that last update, thank you for fixing that! I had been noticing an issue that wasn't more of a problem until I started reusing your mod. There is a config file to not have the game pre-generate colored water. I love the dyed water however I don't love it automatically appearing in the world. There is the option to turn the world-gen of colored water off, however it is written as a **client-side only** config file. Works perfectly as intended in singleplayer but running a server means I once again can't use this mod. There needs to be a common or server config for the world-gen aspect so I can disable it. 

**Is your feature request related to a problem? Yes, or at least a missing feature based off of an existing feature.

I've tried "hard-coding" a world by creating one in single player and moving it over to my server files, however this doesn't work as a solution because any un-generated chunks in the world will continue to allow for HyperLighting water to spawn, even with the configuration off.

A server config for this would be great so I can start reusing! :)

**Comment by hypherionmc** [comment]
Hey. Thanks for the info.

I swapped the config to a "common" config now. If you could test and let me know if it works, I can push a hotfix release for this.

https://ci.firstdarkdev.xyz/job/Hyper%20Lighting/job/1.18.x/lastSuccessfulBuild/artifact/build/libs/HyperLighting-1.18.1-1.2.18d.jar

**Comment by hypherionmc** [comment]
The new release for 1.18.2 should address this issue :)
