### ISSUE TITLE
[BUG] Switch Board Duplicating 

### ISSUE THREAD

**Issue by itsdinkd** [Exploding-Creeper/Hyper-Lighting#13]
**Describe the bug**
Using the switch board, you can duplicate items

**To Reproduce**
1. Check Image
![image](https://user-images.githubusercontent.com/35115304/167028666-bceba13d-1eef-4ef1-8b3a-c89155ac858a.png)

**Expected behavior**

**Screenshots**

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
 - Minecraft Version: Latest 
 - jk, 1.18.2
 - Modloader
 - [ ] Forge
 - [x ] Fabric
 - Mod Loader Version: 0.14.2 and 0.13.3
 - Mod Version:1.2.2

**Additional context**

**Crash Report**

**Comment by hypherionmc** [comment]
Oh crap, that's not good. I'll check this out. I'm working on a couple of bug fixes for a release this weekend so I'll get this sorted for you. Thanks for reporting.

P.S, I'm coming for your kneecaps xD

**Comment by hypherionmc** [comment]
Alright bug confirmed on this one. Will push out a fix by the weekend

**Comment by hypherionmc** [comment]
I suspect this may be an issue across all our custom GUI's with input slots

**Comment by itsdinkd** [comment]
uh oh.. lol. time to remove them on this update I'm releasing, thank you for letting me know

**Comment by hypherionmc** [comment]
Alrighty, this bug has been fixed, just have to check/fix it on forge as well (dunno if it's present there) and will push out a release. Also confirmed, none of our other GUI's are affected by this bug

**Comment by hypherionmc** [comment]
@itsdinkd Release is out for both Forge and Fabric :) Thanks again for reporting. For the next couple of months I'll only be doing bug fix releases on HL, while we work on HL 2
