### ISSUE TITLE
[BUG] Battery Fluorescent Lights become non-interactable when placed on a wall facing west

### ISSUE THREAD

**Issue by M0dEx** [Exploding-Creeper/Hyper-Lighting#17]
**Describe the bug**
`Battery Fluorescent Lights` become non-interactable when placed on a wall facing west.

**To Reproduce**
1. Place a `Battery Fluorescent Light` on a wall facing west
2. Now the light cannot be broken or interacted with.

**Expected behavior**
The light should act normally as if it were placed any other way.

**Screenshots**
![2022-06-16_15 07 06](https://user-images.githubusercontent.com/18428519/174076928-1967e0c3-2b44-42bc-b72c-01eb9a3356ea.png)
![2022-06-16_15 07 10](https://user-images.githubusercontent.com/18428519/174076789-e9ca7d47-9e83-45f4-ae9f-35fbd8d59c31.png)
![2022-06-16_15 07 14](https://user-images.githubusercontent.com/18428519/174076821-510a0ec6-b7f8-4b11-8634-f5884399f814.png)
![2022-06-16_15 07 41](https://user-images.githubusercontent.com/18428519/174076844-ca7e4f39-f0a2-489f-8c89-65f49d55e49d.png)

**Versions:**
 - Minecraft Version: 1.18.2
 - Modloader:
 - - [ ] Forge
 - - [X] Fabric
 - Mod Loader Version: 0.14.8
 - Mod Version: 1.2.3

**Comment by hypherionmc** [comment]
Hey. Thanks for the report. Looks like I missed the bounding box on that model, so the game doesn't know where the bounds of the light are...

**Comment by M0dEx** [comment]
> Hey. Thanks for the report. Looks like I missed the bounding box on that model, so the game doesn't know where the bounds of the light are...

Only when facing one direction, though. If I place it in any other direction, it behaves correctly and as can be seen from the 3rd screenshot, it works rather wonderfully.

**Comment by M0dEx** [comment]
@hypherionmc Made a PR to fix this. I would also recommend checking other branches for this bug as well.

**Comment by M0dEx** [comment]
Solved by #18
