### ISSUE TITLE
[BUG] Not compatible with 1.18.1 fabric

### ISSUE THREAD

**Issue by TheButterbrotMan** [Exploding-Creeper/Hyper-Lighting#2]
https://imgur.com/a/CQTDTyS

**Comment by hypherionmc** [comment]
Wait wth? Oh I see.... I hard coded it to 1.18. I'll release a fix shortly

**Comment by TheButterbrotMan** [comment]
Thank you, for this fast reply. Additonal i would like to ask, if its possible to disable/enable specific lights via config.

**Comment by hypherionmc** [comment]
Can you confirm this fixes the issue before I release it please? https://ci.firstdarkdev.xyz/job/Hyper%20Lighting/job/Fabric/job/1.18.x/3/artifact/build/libs/HyperLightingFabric-1.18.x-1.0.3d.jar

Also by disable, do you mean removing their recipes?

**Comment by TheButterbrotMan** [comment]
Yea, just make them unavailable in game. Removing their recipes would be one way. I can confirm that the fix works. Thank you. Will include it in my modpack.

**Comment by hypherionmc** [comment]
Hmmm, yeah I don't currently have a built in way to disable them, but for now you can replace the recipes. I'll work out something for the next release. Thanks for confirming. Will push a fix now to CF

**Comment by hypherionmc** [comment]
I have released the fix on Curseforge. Can I request that you open a Feature request for the recipes, cause I will forget about it

**Comment by hypherionmc** [comment]
I'm going to close this as the main issue was resolved. Will open a feature request for the recipes
