### ISSUE TITLE
[BUG] Fog Machine unopenable in server environments

### ISSUE THREAD

**Issue by Alkiasan** [Exploding-Creeper/Hyper-Lighting#7]
**Describe the bug**
Fog machines are unopenable on Server Environments

**To Reproduce**
1. Place Fog Machine
2. Attempt to Open

**Expected behavior**
Fog Machine is openable

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
 - Minecraft Version: 1.18.1
 - Modloader
 - [x] Fabric
 - Mod Loader Version: 0.12.2
 - Mod Version: 1.2:
 - [x] Client Side
 - [x] Server Side

**Additional context**
https://pastebin.com/FqmGQc3B

**Comment by hypherionmc** [comment]
Hey. Thanks for reporting. I'll fix it after work. I thought it will be an easy fix but I saw something that may be incorrect, and I just want to make sure it doesn't cause any side effects

**Comment by hypherionmc** [comment]
@Alkiasan sorry for taking so long with this. I was without internet until yesterday. 

Can you please confirm if this build fixes the problem so I can do a release
https://ci.firstdarkdev.xyz/job/Hyper%20Lighting/job/Fabric/job/1.18.x/lastSuccessfulBuild/artifact/build/libs/HyperLightingFabric-1.18.x-1.2.9d.jar

**Comment by Alkiasan** [comment]
Hi, currently waiting for Modrinth to come back online so I can update my out-of-date mods for the server, i'll throw this version of the mod in there too and update you on the results

**Comment by Alkiasan** [comment]
No errors on server, but new error in client?

Unknown custom packed identifier: hyperlighting:opengui

**Comment by Alkiasan** [comment]
Should probably mention that the fog machine still doesn't open

**Comment by hypherionmc** [comment]
@Alkiasan Thanks for your feedback. I appreciate it. I am doing bug fixes and testing with some friends today to get all the remaining bugs sorted

**Comment by hypherionmc** [comment]
Release has been made with a confirmed working fix. Thanks for reporting :)
