### ISSUE TITLE
builtin rgblib

### ISSUE THREAD

**Issue by wackoamd1** [Exploding-Creeper/Hyper-Lighting#8]
**Is your feature request related to a problem? Please describe.**
not realy a problem it just sucks that the mod is for 1.18.1 and rgblib isnt even built for 1.17 ;-(

**Describe the solution you'd like**
colored light to be colored XD or atleast some kind of working rgblib included

**Describe alternatives you've considered**
none

**Additional context**
not complaining but when u  put on the website the handheld candle when rgblib is installed , or colored lights which emit colored light when rgblib is installed atleast make a remark that its NOT working for 1.18.1 or 1.17

**Comment by hypherionmc** [comment]
Very first notice on the Colored Lighting page of the documentation


![Screenshot_20220130_194304_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/63595580/151710827-59ac2364-c8d6-4d69-b276-1ee99aae0ede.jpg)
